USE master;
GO
CREATE DATABASE AmazonDB
GO

USE AmazonDB
GO

CREATE TABLE Roles
(
	RoleId INT CONSTRAINT Roles_PK PRIMARY KEY,
	RoleName VARCHAR(20) CONSTRAINT Roles_NN1 NOT NULL,
	[Description] VARCHAR(100)
)

CREATE TABLE Users
(
	UserId INT CONSTRAINT Users_PK PRIMARY KEY,
	UserName VARCHAR(50) CONSTRAINT Users_NN1 NOT NULL,
	[Password] VARCHAR(50) CONSTRAINT Users_NN2 NOT NULL,
	RoleId INT CONSTRAINT Users_NN3 NOT NULL
)

CREATE TABLE Categories
(
	CategoryId INT CONSTRAINT Categories_PK PRIMARY KEY,
	CategoryName VARCHAR(20) CONSTRAINT Categories_NN1 NOT NULL,
	[Description] VARCHAR(100)
)

CREATE TABLE Products
(
	ProductId INT CONSTRAINT Products_PK PRIMARY KEY,
	ProductName VARCHAR(100) CONSTRAINT Products_NN1 NOT NULL,
	UnitPrice decimal(7,2) CONSTRAINT Products_NN2 NOT NULL,
	AvailableQuantity INT CONSTRAINT Products_NN3 NOT NULL,
	CompanyName VARCHAR(200) CONSTRAINT Products_NN4 NOT NULL,
	CategoryId INT
)

CREATE TABLE Suppliers
(
	SupplierId INT CONSTRAINT Suppliers_PK PRIMARY KEY,
	ContactName VARCHAR(100) CONSTRAINT Suppliers_NN1 NOT NULL,
	[Address] VARCHAR(300) CONSTRAINT Suppliers_NN2 NOT NULL,
	City VARCHAR(100) CONSTRAINT Suppliers_NN3 NOT NULL,
	[State] VARCHAR(100) CONSTRAINT Suppliers_NN4 NOT NULL,
	CompanyName VARCHAR(100) CONSTRAINT Suppliers_NN5 NOT NULL,
	Phone VARCHAR(20) CONSTRAINT Suppliers_NN6 NOT NULL,
	Email VARCHAR(100),
	ProductId INT
)

CREATE TABLE Customers
(
	CustomerId INT CONSTRAINT Customers_PK PRIMARY KEY,
	ContactName VARCHAR(100) CONSTRAINT Customers_NN1 NOT NULL,
	[Address] VARCHAR(300) CONSTRAINT Customers_NN2 NOT NULL,
	City VARCHAR(100) CONSTRAINT Customers_NN3 NOT NULL,
	[State] VARCHAR(100) CONSTRAINT Customers_NN4 NOT NULL,
	Country VARCHAR(100) CONSTRAINT Customers_NN5 NOT NULL,
	Phone VARCHAR(20) CONSTRAINT Customers_NN6 NOT NULL,
	Email VARCHAR(100),
	UserId INT
)

CREATE TABLE Orders
(
	OrderId INT CONSTRAINT Orders_PK PRIMARY KEY,
	OrderDate DATETIME CONSTRAINT Orders_NN1 NOT NULL,
	DeliveryDate DATETIME CONSTRAINT Orders_NN2 NOT NULL,
	CustomerId INT CONSTRAINT Orders_NN3 NOT NULL
)

CREATE TABLE OrderDetails
(
	ProductId INT CONSTRAINT OrderDetails_NN1 NOT NULL,
	OrderId INT CONSTRAINT OrderDetails_NN2 NOT NULL,
	Quantity INT CONSTRAINT OrderDetails_NN3 NOT NULL,
	DiscountPercentage INT
)

CREATE TABLE Invoices
(
	InvoiceId INT CONSTRAINT Invoices_PK PRIMARY KEY,
	OrderId INT,
	InvoiceDate DATETIME
)

ALTER TABLE Users ADD CONSTRAINT Users_FK FOREIGN KEY(RoleId) REFERENCES Roles(RoleId)

ALTER TABLE Products ADD CONSTRAINT Products_FK FOREIGN KEY(CategoryId) REFERENCES Categories(CategoryId)

ALTER TABLE Suppliers ADD CONSTRAINT Suppliers_FK FOREIGN KEY(SupplierId) REFERENCES Products(ProductId)

ALTER TABLE Customers ADD CONSTRAINT Customers_FK FOREIGN KEY(UserId) REFERENCES Users(UserId)

ALTER TABLE Orders ADD CONSTRAINT Orders_FK FOREIGN KEY(CustomerId) REFERENCES Customers(CustomerId)

ALTER TABLE OrderDetails ADD CONSTRAINT OrderDetails_PK PRIMARY KEY (ProductId,OrderId)

ALTER TABLE OrderDetails ADD CONSTRAINT OrderDetails_FK1 FOREIGN KEY (OrderId) REFERENCES Orders(OrderId)

ALTER TABLE OrderDetails ADD CONSTRAINT OrderDetails_FK2 FOREIGN KEY (ProductId) REFERENCES Products(ProductId)

ALTER TABLE Invoices ADD CONSTRAINT Invoices_FK1 FOREIGN KEY (OrderId) REFERENCES Orders(OrderId)